#!/usr/bin/env bash
set -eu -o pipefail

RESULT="$(nix-build --no-out-link -E 'let this = import ./.; nixpkgs = this.nixpkgs; in nixpkgs.androidenv.emulateApp { name = "focus"; app = this.android; platformVersion = "23"; enableGPU = true; abiVersion = "x86_64"; useGoogleAPIs = false; package = "systems.obsidian.focus"; activity = ".MainActivity";}')"

"$RESULT/bin/run-test-emulator"
