#!/usr/bin/env bash
set -eu -o pipefail
echo -ne '\033]0;BACKEND\007'
exec nix-shell -E 'let this = import ./. { enableProfiling = true; }; in this.backend.env' --run '\
  mkdir -p dist-backend; \
  ghc Main -threaded -i{common,backend,frontend}/src -outputdir dist-backend -o dist-backend/backendExec -DUSE_TEMPLATE_HASKELL -DBACKEND -O0; \
  ghc Main -threaded -i{common,backend,frontend}/src -outputdir dist-backend -o dist-backend/backendExecP -DUSE_TEMPLATE_HASKELL -DBACKEND -O0 \
  -prof -fprof-auto -Ldist-backend \
  -hcsuf hc_p -hisuf hi_p -osuf o_p -dynosuf dyno_p -dynhisuf dynhi_p' \
  "$@"

# GC flags
# If BUSY_YIELD < SCHED_QUANTUM, only one thread ever seems to get to run.
# -DGHCJS_GC_INTERVAL=60000 -DGHCJS_BUSY_YIELD=5 -DGHCJS_SCHED_QUANTUM=5

# Xtreme optimization
# -O2 -fplugin=Reflex.Optimizer -fexpose-all-unfoldings -fspecialise-aggressively

# dump ghc intermediate outputs for analysis
# -dumpdir=dump-js -ddump-to-file -ddump-simpl -ddump-hi -dppr-cols=200 -ddump-rule-firings -dsuppress-all
