#!/usr/bin/env bash
set -eu -o pipefail
echo -ne '\033]0;FRONTEND\007'
nix-shell -A frontendGhc.env --run 'ghc -i{common,frontend}/src Main -outputdir dist-frontend-ghc -fplugin=Reflex.Optimizer -O2 -fexpose-all-unfoldings -funfolding-creation-threshold=1000000 -ddump-rule-firings -ddump-simpl -ddump-simpl-stats -ddump-hi -ddump-to-file'
