#!/usr/bin/env bash
set -euo pipefail

echo -ne '\033]0;FRONTEND-GHC-WKWEBVIEW\007'

OLDPWD="$PWD"
BUILDDIR="$PWD/dist-ghc-wkwebview"
mkdir -p "$BUILDDIR"
CABAL_FILE="$(nix-build --no-out-link -A frontendGhcWKWebView.cabalFile --show-trace)"
TMPDIR="$(mktemp -d 2>/dev/null || mktemp -d -t frontend-ghc-wkwebbview)"
function cleanup {
  rm -rf "$TMPDIR"
}
trap cleanup EXIT

nix-shell --show-trace -A frontendGhcWKWebView --run "
cd "$TMPDIR"
shopt -s nullglob
ln -s "$OLDPWD"/{common,frontend}/src{,-bin}/* .
shopt -u nullglob
ln -s "$CABAL_FILE" frontend-ghc-wkwebview.cabal
ln -s "$BUILDDIR" dist
"'
function setupCompilerEnvironmentPhase {
  eval "$setupCompilerEnvironmentPhase"
}
setupCompilerEnvironmentPhase
function compileBuildDriverPhase {
  eval "$compileBuildDriverPhase"
}
compileBuildDriverPhase
eval "$configurePhase"
set -e
eval "$(echo "$buildPhase" | sed '\''s/Setup build /Setup build mobile /'\'')"
'

open $(nix-build --no-out-link -E "(import ./. {}).mkMacApp \"wrinkl\" \"com.wrinkl.ios\" \"mobile\" $BUILDDIR/build/mobile ./static")/mobile.app
