#!/usr/bin/env bash
set -euo pipefail
if [ $# -ne 0 ]; then
  echo "Usage: $0" >&2
  exit 1
fi

echo -ne '\033]0;FRONTEND-IOS-AARCH64\007'

OLDPWD="$PWD"
BUILDDIR="$PWD/dist-ios-aarch64"
mkdir -p "$BUILDDIR"
CABAL_FILE="$(nix-build --no-out-link -A frontendIosAArch64.cabalFile --show-trace)"
TMPDIR="$(mktemp -d 2>/dev/null || mktemp -d -t frontend-ios-aarch64)"
function cleanup {
  rm -rf "$TMPDIR"
}
trap cleanup EXIT

nix-shell --show-trace -A frontendIosAArch64 --run "
cd "$TMPDIR"
shopt -s nullglob
ln -s "$OLDPWD"/{common,frontend}/src{,-bin}/* .
shopt -u nullglob
ln -s "$CABAL_FILE" frontend-ios-aarch64.cabal
ln -s "$BUILDDIR" dist
"'
function setupCompilerEnvironmentPhase {
  eval "$setupCompilerEnvironmentPhase"
}
setupCompilerEnvironmentPhase
function compileBuildDriverPhase {
  eval "$compileBuildDriverPhase"
}
compileBuildDriverPhase
eval "$configurePhase"
set -e
eval "$(echo "$buildPhase" | sed '\''s/Setup build /Setup build mobile /'\'')"
'
if [ ! -e $BUILDDIR/bin ]; then
  ln -s $BUILDDIR/build/mobile $BUILDDIR/bin
fi

COMMIT_COUNT=$(git rev-list HEAD --count)

echo $(nix-build --no-out-link -E "
  let this = import ./. {};
  in this.mkIosApp {
    bundleVersion = \"$COMMIT_COUNT\";
    package = p: $BUILDDIR;
  }")/bin/deploy "$@"
