#!/usr/bin/env bash
set -euo pipefail

echo -ne '\033]0;FRONTEND-ANDROID-AARCH64\007'

OLDPWD="$PWD"
BUILDDIR="$PWD/dist-ios-sim"
mkdir -p "$BUILDDIR"
CABAL_FILE="$(nix-build --no-out-link -A frontendAndroidAArch64.cabalFile --show-trace)"
TMPDIR="$(mktemp -d 2>/dev/null || mktemp -d -t frontend-android-aarch64)"
function cleanup {
  rm -rf "$TMPDIR"
}
trap cleanup EXIT

nix-shell --show-trace -A frontendAndroidAArch64 --run "
cd "$TMPDIR"
shopt -s nullglob
ln -s "$OLDPWD"/{common,frontend}/src{,-bin}/* .
shopt -u nullglob
ln -s "$CABAL_FILE" frontend-android-aarch64.cabal
ln -s "$BUILDDIR" dist
"'
function setupCompilerEnvironmentPhase {
  eval "$setupCompilerEnvironmentPhase"
}
setupCompilerEnvironmentPhase
function compileBuildDriverPhase {
  eval "$compileBuildDriverPhase"
}
compileBuildDriverPhase
eval "$configurePhase"
eval "$(echo "$buildPhase" | sed '\''s/Setup build /Setup build aspen-frontend-clib /'\'')"
return $?
'
