#!/usr/bin/env bash
set -eu -o pipefail
echo -ne '\033]0;FRONTEND\007'
nix-shell -A frontendGhc.env --run 'ghc -i{common,frontend}/src Main -outputdir dist-frontend-ghc -fexpose-all-unfoldings -funfolding-creation-threshold=1000000 -ddump-rule-firings -ddump-simpl -ddump-simpl-stats -ddump-hi -ddump-to-file -DUSE_WARP -DUSE_TEMPLATE_HASKELL'
