#!/usr/bin/env bash
set -eu -o pipefail
echo -ne '\033]0;FRONTEND\007'
#nix-shell -A frontendGhc.env --run 'ghc -i{common,frontend}/src Main -DUSE_WARP -DUSE_TEMPLATE_HASKELL -DDUMPING_SPLICES -outputdir dist-frontend-dump-splices -ddump-splices -ddump-to-file -dth-dec-file -framework-path /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -O0 -no-link -fforce-recomp'

for x in $(cd dist-frontend-dump-splices ; find . -name '*.dump-splices') ; do
    # See ./dump-splices for an explanation of these sed transformations
    ( cat "dist-frontend-dump-splices/$x" && echo "--" ) | sed -e 's/^    //' | sed -e '/Splicing [a-z]*$/,/^  ======>$/ s/^/-- /' -e 's/\b\(case .*\) {$/\1/' -e '/ })*$/{N;s/ }\()*\)\(\n\|$\)\( \{0,2\}\([^ ]\|$\)\)/\1\2\3/;P;D}' > "$(echo "$x" | sed 's/.dump-splices$/.splices.hs/')"
done
