#!/usr/bin/env bash
set -eu -o pipefail
echo -ne '\033]0;FRONTEND\007'
nix-shell -A frontendGhc.env --run 'ghc -i{common,frontend}/src Main -DUSE_WARP -DMOBILE -DUSE_TEMPLATE_HASKELL -DDUMPING_SPLICES -outputdir dist-frontend-dump-splices -ddump-splices -ddump-to-file -dth-dec-file -framework-path /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -j4 -O0 -no-link'
for x in $(find frontend/src-bin -name '*.hs') ; do
    nix-shell -A frontendGhc.env --run 'ghc -i{common,frontend}/src '"$x"' -DUSE_WARP -DMOBILE -DUSE_TEMPLATE_HASKELL -DDUMPING_SPLICES -outputdir dist-frontend-dump-splices -ddump-splices -ddump-to-file -dth-dec-file -framework-path /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -j4 -O0 -no-link'
done

for x in $(cd dist-frontend-dump-splices ; find . -name '*.dump-splices') ; do
    # See ./dump-splices for an explanation of these sed transformations
    ( cat "dist-frontend-dump-splices/$x" && echo "--" ) | sed -e 's/^    //' | sed -e '/Splicing [a-z]*$/,/======>$/ s/^/-- /' -e 's/\b\(case .*\) {$/\1/' -e '/ })*$/{N;s/ }\()*\)\n\( \{0,2\}\([^ ]\|$\)\)/\1\n\2/;P;D}' -e 's/\b\(aeson\|base\)-[0-9.]*://' -e 's/Data.OldList/Data.List/' > "$(echo "$x" | sed 's/.dump-splices$/.splices.hs/')"
done
