#!/usr/bin/env bash
set -eu -o pipefail

nix-shell -E 'let this = import ./.; lib = import "${this.nixpkgs.path}/pkgs/development/haskell-modules/lib.nix" { pkgs = this.nixpkgs; }; in (lib.addBuildDepend this.tests this.tests.haskellPackages.ghcid).env' --command "ghcid -c'ghci -itests/src Main -hide-package cryptonite'" "$@"
