#!/usr/bin/env bash
set -eu

nix-shell -E 'let this = import ./. {}; lib = this.tryReflex.nixpkgs.haskell.lib; in (lib.addBuildDepend this.frontendGhc this.frontendGhc.haskellPackages.ghcid).env' --command "ghcid --test=writeFrontendCss -c'ghci -O0 -fno-code -XNoNondecreasingIndentation -Wall -ifrontend/src Frontend.CSS'" "$@"
