#!/usr/bin/env bash
set -eu

FOCUS_PACKAGE="$1"
shift

exec nix-shell -E 'let this = import ./. {}; lib = this.tryReflex.nixpkgs.haskell.lib; in (lib.addBuildDepends this.backend.haskellPackages.focus-'"$FOCUS_PACKAGE"' [ this.backend.haskellPackages.ghcid this.backend.haskellPackages.ghcid this.backend.haskellPackages.cabal-install ]).env' --run "exec cd \"focus/$FOCUS_PACKAGE\" && cabal configure --builddir=dist-ghci --ghc-option=-w && cabal repl --builddir=dist-ghci --ghc-option=-Wall" "$@"
