#!/usr/bin/env bash
set -eu
echo -ne '\033]0;BACKEND\007'
exec nix-shell -E 'let this = import ./. {}; lib = this.tryReflex.nixpkgs.haskell.lib; in this.backend.env' --command "exec ghci -ibackend/src -icommon/src Main -hide-package cryptonite" "$@"
