#!/usr/bin/env bash
set -eu

nix-shell -E 'let this = import ./. {}; lib = import "${this.nixpkgs.path}/pkgs/development/haskell-modules/lib.nix" { pkgs = this.nixpkgs; }; in (lib.addBuildDepends this.backend [this.backend.haskellPackages.ghcid this.nixpkgs.postgresql95]).env' --command "ghcid -c'ghci -Wall'" "$@"
