#!/usr/bin/env bash
set -eu
echo -ne '\033]0;BACKEND\007'
exec nix-shell -E 'let this = import ./. {}; lib = this.tryReflex.nixpkgs.haskell.lib; in this.backend.env' --run "exec ghci -Wall -DBACKEND -DUSE_TEMPLATE_HASKELL -icommon/src -ibackend/src -ifrontend/src Main" "$@"
