#!/usr/bin/env bash
set -eu

nix-shell -E 'let this = import ./. {}; lib = this.tryReflex.nixpkgs.haskell.lib; in (lib.addBuildDepend this.frontendGhc this.frontendGhc.haskellPackages.ghcid).env' --command "ghcid -c'ghci -Wall -ifocus/core/src -ifocus/js/src -icommon/src -ifrontend/src Main'" "$@"
