#!/usr/bin/env bash
set -eu -o pipefail

nix-shell -E 'let this = import ./. {}; lib = this.tryReflex.nixpkgs.haskell.lib; in (lib.addBuildDepend this.tests this.tests.haskellPackages.ghcid).env' --command "ghcid -c'ghci -Wall -icommon/src -itests/src -ibackend/src Main -hide-package cryptonite'" "$@"

