#!/usr/bin/env bash
set -eu
echo -ne '\033]0;BACKEND\007'
nix-shell -E 'let this = import ./.; lib = import "${this.nixpkgs.path}/pkgs/development/haskell-modules/lib.nix" { pkgs = this.nixpkgs; }; in this.commonBackend.env' --command "ghci -icommon/src -hide-package cryptonite" "$@"
