#!/usr/bin/env bash
set -eu -o pipefail

nix-shell -E 'let this = import ./. {}; lib = this.tryReflex.nixpkgs.haskell.lib; in (lib.addBuildDepend this.frontendGhc this.frontendGhc.haskellPackages.ghcid).env' --command "ghci -icommon/src -ifrontend/src -DUSE_WARP -DUSE_TEMPLATE_HASKELL Main" "$@"
