#!/usr/bin/env bash
set -eu

exec nix-shell -E 'let this = import ./. {}; lib = this.tryReflex.nixpkgs.haskell.lib; in (lib.addBuildDepend this.frontendGhc this.frontendGhc.haskellPackages.ghcid).env' --run "exec ghcid --test=writeFrontendCss -c'ghci -O0 -XNoNondecreasingIndentation -ifrontend/src Frontend.CSS'" "$@"
