#!/usr/bin/env bash
set -euo pipefail

echo -ne '\033]0;FRONTEND-IOS-AARCH64\007'

cp `nix-build --no-out-link -A frontendIosAArch64.cabalFile --show-trace` aspen-frontend.cabal

OLDPWD="$PWD"
BUILDDIR="$PWD/dist-ios-aarch64"
mkdir -p "$BUILDDIR"
CABAL_FILE="$(nix-build --no-out-link -A frontendIosAArch64.cabalFile --show-trace)"
TMPDIR="$(mktemp -d 2>/dev/null || mktemp -d -t frontend-ios-aarch64)"
function cleanup {
  rm -rf "$TMPDIR"
}
trap cleanup EXIT

nix-shell --show-trace -A frontendIosAArch64 --run "
cd "$TMPDIR"
shopt -s nullglob
ln -s "$OLDPWD"/{common,frontend}/src{,-bin}/* .
shopt -u nullglob
ln -s "$CABAL_FILE" frontend-ios-aarch64.cabal
ln -s "$BUILDDIR" dist
"'
function setupCompilerEnvironmentPhase {
  eval "$setupCompilerEnvironmentPhase"
}
setupCompilerEnvironmentPhase
function compileBuildDriverPhase {
  eval "$compileBuildDriverPhase"
}
compileBuildDriverPhase
eval "$configurePhase"
set -e
unset GHC_PACKAGE_PATH
eval "$(echo "$buildPhase" | sed '\''s/\.\/Setup build \(.*\)$/\(cd ~\/haskell\/aspen \&\& nix-shell -A frontendIosAArch64.env --run "cabal new-configure \1 \&\& leksah"\)/'\'')"
'

$(nix-build --no-out-link -E "(import ./. {}).mkIosApp \"mobile\" dist-newstyle/build/aarch64-ios/ghc-8.1.20170106/aspen-frontend-0.1/c/mobile/build/mobile ./static")/bin/deploy "$@"
