#!/usr/bin/env bash
set -eu -o pipefail

TESTS="$(nix-build --no-out-link -A tests)"
BACKEND="$(nix-build --no-out-link -A backend)"

"$TESTS/bin/tests" "$BACKEND/bin/backend" || pkill backend #TODO: Not needing this

#TODO: Not needing this
pkill backend
