#!/usr/bin/env bash
set -euo pipefail

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

HOSTNAME="$1"
shift
CONFIG="$1"
shift

TEMP=$(mktemp -d)
trap "rm -rf $(printf "%q" "$TEMP") ; pkill -P $$" EXIT

eval "$(ssh-agent)"
ssh-keygen -f "$TEMP/key" -N ""
ssh-add "$TEMP/key"

mkfifo "$TEMP/pipe"

VM="$(nix-build --no-out-link -A completeServer.qemu.vm --argstr hostName "$HOSTNAME" --argstr extraRootKey "$(cat "$TEMP/key.pub")" "$@")"

if [ -z "$VM" ] ; then
    echo "Build failed" 2>&1
    exit 1
fi

NIX_DISK_IMAGE="$TEMP/disk" "$VM/bin/run-$HOSTNAME-vm" | tee --output-error=warn "$TEMP/pipe" 2>/dev/null &
QEMU_INFO_BLOCK_DELIMITER="$(eval "echo $(nix-instantiate --eval -E '(import ./.).qemuInfoBlockDelimiter')")"

eval "$(sed -n -e "/BEGIN $QEMU_INFO_BLOCK_DELIMITER/,/END $QEMU_INFO_BLOCK_DELIMITER/{//!p}" -e "/END $QEMU_INFO_BLOCK_DELIMITER/q" <"$TEMP/pipe" | tr -d '\r')"
rm "$TEMP/pipe"

if [ -z "${MY_IP+x}" ] ; then
    echo "VM exited without producing expected values" 2>&1
    exit 1
fi

echo ",$MY_IP $MY_HOST_KEY" > "$TEMP/known_hosts"

SSH="ssh -o UserKnownHostsFile=$TEMP/known_hosts"
TARGET="root@$MY_IP"

"$DIR/deploy-config" "$SSH" "$TARGET" "$CONFIG"

$SSH "$TARGET" bash <<EOF
  sleep 1 # Without this, we sometimes get errors like this: "<command line>: can't load .so/.DLL for: /nix/store/hsww8cgczlp2q2c2rbrabbkg3s98fcjw-cereal-0.5.1.0/lib/ghc-8.0.1/cereal-0.5.1.0/libHScereal-0.5.1.0-JK5wdtcV0iTGsZDqLKxNfI-ghc8.0.1.so (/nix/store/hsww8cgczlp2q2c2rbrabbkg3s98fcjw-cereal-0.5.1.0/lib/ghc-8.0.1/cereal-0.5.1.0/libHScereal-0.5.1.0-JK5wdtcV0iTGsZDqLKxNfI-ghc8.0.1.so: cannot open shared object file: Interrupted system call)" #TODO: Investigate this
  systemctl restart backend
EOF

wait
